name: Manual Production Build

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create release'
        required: false
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build VideoRenderer
        shell: pwsh
        run: |
          .\build_mpcvr.cmd NoWait

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "Manual-Production-Build"
          path: |
            _bin/**/*.ax
            _bin/**/*.zip